dist: trusty
sudo: required

language: android

jdk:
  - openjdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

before_script:
  - echo "org.gradle.configureondemand=true" > $HOME/.gradle/gradle.properties
  - echo "org.gradle.jvmargs=-Xmx1536M" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.caching=true" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.parallel=true" >> $HOME/.gradle/gradle.properties


script:
  - ./gradlew build -s

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
